apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "seafile.fullname" . }}
  labels:
{{ include "seafile.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "seafile.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "seafile.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: seafile
          persistentVolumeClaim:
            claimName: {{ .Values.db.volumeClaimName }}
      containers:
        - name: seafile-mysql
          image: {{ .Values.db.image }}
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: seafile
              subPath: mysql
          resources:
            requests:
              cpu: 400m
          env:
{{ toYaml .Values.db.environment | indent 10 }}
        - name: seafile-memcached
          image: {{ .Values.memcached.image }}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 400m
          command: ["memcached"]
          args: ["-m", "256"]
        - name: seafile
          image: {{ .Values.seafile.image }}
          securityContext:
            privileged: true
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/shared"
              name: seafile
              subPath: seafile
          resources:
            requests:
              cpu: 400m
          env:
{{ toYaml .Values.seafile.environment | indent 10 }}
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
